### ISSUE TITLE
Not working on Scala 3.7.4 and Scalafix 0.14.4

### ISSUE THREAD

**Issue by enrico-benini** [jatcwang/scalafix-named-params#194]
[In this branch](https://github.com/benkio/sBots/tree/827) that just adds the required `scalac` option to `sbt` I receive the following error:

```
sbt:sBots> scalafix dependency:UseNamedParameters@com.github.jatcwang:scalafix-named-params:0.2.5

scalafix dependency:UseNamedParameters@com.github.jatcwang:scalafix-named-params:0.2.5

[info] Loading external rule(s) built against an old version of Scalafix (0.13.0).
[info] This might not be a problem, but in case you run into unexpected behavior, you
[info] should try a more recent version of the rules(s) if available. If that does
[info] not help, request the rule(s) maintainer to build against Scalafix 0.14.4
[info] or later, and downgrade Scalafix to 0.13.x for the time being.
[info]               
[info] compiling 45 Scala sources to /Users/benkio/playground/sBots/modules/telegramBotInfrastructure/target/scala-3.7.4/classes ...
[error] bad option: -P:semanticdb:synthetics:on
[error] one error found
[error] (telegramBotInfrastructure / Compile / compileIncremental) Compilation failed
[error] Total time: 4 s, completed 13 Nov 2025, 11:05:35
```

Could it be because of scala 3.7.4 or the latest version of scalafix.

**Comment by jatcwang** [comment]
Published. Please yell of it doesn't work :)
